title: Fabian Schilling
email: ""
tagline: "Student of Computer Science · Robotics Research Engineer · Deep Learning Enthusiast"
baseurl: ""
url: "http://fabianschilling.github.io"
paginate: 1
github_username: fabianschilling

gems:
  - jekyll-paginate

markdown: kramdown
permalink: pretty
