title: Fabian Schilling
email: ""
tagline: "PhD Student in Robotics, Control, and Intelligent Systems at EPFL"
baseurl: ""
url: "http://fabianschilling.github.io"
paginate: 1
github_username: fabianschilling

plugins:
  - jekyll-paginate

markdown: kramdown
permalink: pretty

google_analytics: UA-96749476-1
